### ISSUE TITLE
BetterBags Bug

### ISSUE THREAD

**Issue by Imiona** [p3lim-wow/Molinari#134] opened 2024-02-08 12:36 UTC
**Describe the bug**

Happens with BetterBags, succesor to AdiBags who will no longer be developed.

<details>
  <summary>Click to expand</summary>
  1x Molinari/addon.lua:122: Action[SetPoint] failed because[Failure]: attempted from: Molinari:SetAllPoints.
[string "=[C]"]: in function `SetAllPoints'
[string "@Molinari/addon.lua"]:122: in function <Molinari/addon.lua:120>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Molinari/addon.lua"]:75: in function <Molinari/addon.lua:56>
[string "=(tail call)"]: ?
[string "@Molinari/utils.lua"]:20: in function <Molinari/utils.lua:5>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML/ContainerFrame.lua"]:1519: in function `OnUpdate'
[string "@FrameXML/ContainerFrame.lua"]:1486: in function `OnEnter'
[string "@FrameXML/ContainerFrame.lua"]:1482: in function <FrameXML/ContainerFrame.lua:1481>

Locals:
(*temporary) = Molinari {
 0 = <userdata>
 ApplySpell = <function> defined @Molinari/addon.lua:56
 IsEventRegistered = <function> defined @Molinari/libs/Dashi/modules/event.lua:76
 TriggerCombatEvent = <function> defined @Molinari/libs/Dashi/modules/event.lua:222
 RegisterCombatEvent = <function> defined @Molinari/libs/Dashi/modules/event.lua:227
 RegisterUnitEvent = <function> defined @Molinari/libs/Dashi/modules/event.lua:119
 UnregisterUnitEvent = <function> defined @Molinari/libs/Dashi/modules/event.lua:151
 TriggerEvent = <function> defined @Molinari/libs/Dashi/modules/event.lua:89
 RegisterEvent = <function> defined @Molinari/libs/Dashi/modules/event.lua:40
 TriggerUnitEvent = <function> defined @Molinari/libs/Dashi/modules/event.lua:196
 UnregisterCombatEvent = <function> defined @Molinari/libs/Dashi/modules/event.lua:245
 ApplyItem = <function> defined @Molinari/addon.lua:79
 IsUnitEventRegistered = <function> defined @Molinari/libs/Dashi/modules/event.lua:176
 AddSparkles = <function> defined @Molinari/addon.lua:91
 CalculateAction = <function> defined @FrameXML/SecureTemplates.lua:609
 sparkles = <table> {
 }
 UnregisterEvent = <function> defined @Molinari/libs/Dashi/modules/event.lua:58
 UpdateAttributeDriver = <function> defined @Molinari/addon.lua:96
}
(*temporary) = BetterBagsItemButton169 {
 0 = <userdata>
 OnLeave = <function> defined @FrameXML/ContainerFrame.lua:1493
 SetItem = <function> defined @FrameXML/ItemButtonTemplate.lua:544
 OnHide = <function> defined @FrameXML/ContainerFrame.lua:1585
 SetItemButtonQuality = <function> defined @FrameXML/ItemButtonTemplate.lua:662
 IconOverlay = Texture {
 }
 __MSQ_SetItemButtonTexture = true
 __MSQ_bType = "Item"
 SetAlpha = <function> defined @FrameXML/ItemButtonTemplate.lua:631
 UpdateCooldown = <function> defined @FrameXML/ContainerFrame.lua:1704
 ItemSlotBackground = Texture {
 }
 showMatchHighlight = true
 OnDragStart = <function> defined @FrameXML/ContainerFrame.lua:1591
 OnReceiveDrag = <function> defined @FrameXML/ContainerFrame.lua:1595
 icon = BetterBagsItemButton169IconTexture {
 }
 PostOnEvent = <function> defined @FrameXML/ItemButtonTemplate.lua:427
 isExtended = false
 __MSQ_PushedColor = <table> {
 }
 UpdateTooltip = <function> defined @FrameXML/ContainerFrame.lua:1504
 SetReadable = <function> defined @FrameXML/ContainerFrame.lua:1696
 CheckUpdateTooltip = <function> defined @FrameXML/ContainerFrame.lua:1720
 __MSQ_Scale = 1
 UpdateNewItem = <function> defined @FrameXML/ContainerFrame.lua:1642
 IsReadable = <function> defined @FrameXML/ContainerFrame.lua:1700
 __MSQ_NormalHook = true
 JunkIcon = Texture {
 }
 count = 1
 UpdateItemContextMatching = <function> defined @FrameXML/ItemButtonTemplate.lua:450
 SetNormalAtlas = <function> defined =[C]:-1
 SetItemButtonCount = <function> defined @FrameXML/ItemButtonTemplate.lua:614
 __MSQ_Normal = Texture {
 }
 SetItemInternal = <function> defined @FrameXML/ItemButtonTemplate.lua:549
 __MSQ_NormalSkin = <table> {
 }
 UpdateCraftedProfessionsQualityShown = <function> defined @FrameXML/ItemButtonTemplate.lua:461
 HighlightTexture = Texture {
 }
 __MSQ_NewNormal = Texture {
 }
 PixelSnapDisabled = true
 PostOnShow = <function> defined @FrameXML/ItemButtonTemplate.lua:414
 UpdateItemContextOverlayTextures = <function> defined @FrameXML/ItemButtonTemplate.lua:499
 __MSQ_Enabled = true
 SetItemSource = <function> defined @FrameXML/ItemButtonTemplate.lua:528
 __MSQ_NormalColor = <table> {
 }
 flash = Texture {
 }
 IconQuestTexture = BetterBagsItemButton169IconQuestTexture {
 }
 hasItem = 1
 __MSQ_Backdrop = Texture {
 }
 SetBagID = <function> d
</details>

**Comment by p3lim** [comment] 2024-02-08 19:02
Duplicate of #129, just haven't released an update yet.

**Closed by p3lim** 2024-02-08 19:02 UTC
Labels: bug
