### ISSUE TITLE
Whitelist Feature

### ISSUE THREAD

**Issue by papasoldragon** [p3lim-wow/Molinari#23] opened 2017-11-05 02:02 UTC
I was wondering if you could add a whitelist function that serves the opposite function of the blacklist. Forces an action on an item. For instance, there are several profession question items that are not supported by this addon, Specifically ones like  ID 137195 (Highmountain Armor) quest green for enchanting quest. 

I run multiple Enchanters so I've gone through these types of quests several times, I would be nice if I can add a item to a whitelist to force the disenchant. Configuration could be as simple as holding alt and right clicking an item to record the item ID and checking for professions to figure out if it's disenchant, mill or prospecting. (open a dialog to have the user confirm if they have more than one these professions)

Anyways, it would be nice but I thank you for your wonderful work here. I find this addon a must have now days.

**Comment by p3lim** [comment] 2017-11-05 02:35
Those quest items were added in 70300.50-Release about two months ago.

**Comment by p3lim** [comment] 2018-06-19 14:42
Somewhat duplicate of #24, which has now been fixed.
A whitelist would be nice, but I don't see it as worth the effort of implementing.

**Closed by p3lim** 2018-06-19 14:42 UTC
