### ISSUE TITLE
Classic Error Upon Logging In

### ISSUE THREAD

**Issue by Comicus** [p3lim-wow/Molinari#37] opened 2019-12-11 02:43 UTC
If you're opening a feature request, please search through the existing issues first.  
If you're submitting an issue, please fill in the following:

- What version are you using?
Molinari-80200.63-Release-classic.zip
- Can the issue be reproduced, and if so, how?
_ it happens when I log in_
- If there was an error message, please include it.
7x ...dOns\Molinari\libs\LibProcessable\LibProcessable-37.lua:264: attempt to call global 'GetProfessions' (a nil value)
...dOns\Molinari\libs\LibProcessable\LibProcessable-37.lua:264: in function <...dOns\Molinari\libs\LibProcessable\LibProcessable.lua:250>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "SKILL_LINES_CHANGED"
(*temporary) = nil
(*temporary) = "attempt to call global 'GetProfessions' (a nil value)"
professions = <table> {
}
CLASSIC = false
classicIDs = <table> {
 Tailoring = 197
 Blacksmithing = 164
 Skinning = 393
 Alchemy = 171
 Mining = 186
 Engineering = 202
 Leatherworking = 165
 Herbalism = 182
 Enchanting = 333
}
- If there is a graphical issue, please include a screenshot (you can drag-n-drop here).
none 
Make sure you check back often until the issue is resolved for any follow-up questions.

**Comment by p3lim** [comment] 2019-12-12 13:38
Duplicate of #36

**Comment by rainfordays** [comment] 2019-12-12 14:29
There are two pull requests added to the LibProcessable git that addresses this issue. @p3lim choose whichever you like. The CVar one should be future-proof.

**Comment by p3lim** [comment] 2019-12-14 19:55
Fixed in https://github.com/p3lim-wow/LibProcessable/pull/30.

**Closed by p3lim** 2019-12-14 19:55 UTC
