### ISSUE TITLE
bug with new release?

### ISSUE THREAD

**Issue by docgibbons** [p3lim-wow/Molinari#168] opened 2024-08-19 04:03 UTC
**Describe the bug**
when logging into the game

**How to reproduce**
i had just updated to the new release

Date: 2024-08-19 00:00:46
ID: 1
Error occured in: Global
Count: 1
Message: ...terface/AddOns/Molinari/libs/Dashi/modules/event.lua line 121:
   ...face/AddOns/Molinari/libs/Dashi/modules/settings.lua line 179:
   attempt to call field 'CreateDropdown' (a nil value)
Debug:
   [string "=[C]"]: error()
   [string "@Interface/AddOns/Molinari/libs/Dashi/modules/event.lua"]:121: TriggerEvent()
   [string "@Interface/AddOns/Molinari/libs/Dashi/modules/event.lua"]:132:
      ...terface/AddOns/Molinari/libs/Dashi/modules/event.lua:131
Locals:
(*temporary) = "...face/AddOns/Molinari/libs/Dashi/modules/settings.lua:179: attempt to call field 'CreateDropdown' (a nil value)"

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  Auctionator, v11.0.9
  BagBrother, v
  Bagnon, v11.0.4
  BagnonScrap, v10.2.1
  ChatCopyPaste, v1.22
  CurrencyTracking, vv7.16
  DBMCore, v11.0.2
  DBMCountPackHotS, v1.7.38
  DBMCountPackOverwatch, v1.4.42
  DBMSMGEventsPack, v1.5.37
  DBMSoundEventsPack, v1.6.36
  DBMSpellTimers, vr157
  DBMStatusBarTimers, v11.0.2
  DBMVPVEM, veeae112
  Details, v#Details.12805.158-1-g8d65e6a
  ExtendedCharacterStats, v3.3.6
  GrimoireKeeper, v1.2
  Guidelime, v4.005
  Guidelimeahmp, v1.4
  GuidelimeCowcium, v1
  GuidelimeMarkyMark, vv1.8
  GuidelimeSage, v2.23
  GuideLimeTUGsWOTLK, v3.141
  LFGBulletinBoard, v3.36
  LootReserve, v2024-08-18
  Molinari, v110000.118-Release
  Questie, v10.3.12
  Scrap, v11.0.2
  BlizRuntimeLib_enUS v1.15.3.11503 <none>
  (ck=319)

**Comment by docgibbons** [comment] 2024-08-19 04:08
i installed the previous version and it cleared the error

**Comment by p3lim** [comment] 2024-08-19 09:14
Duplicate of #167

**Closed by p3lim** 2024-08-19 09:14 UTC
Labels: bug
