### ISSUE TITLE
Classic not working for enchanting since update

### ISSUE THREAD

**Issue by gigglz** [p3lim-wow/Molinari#38] opened 2019-12-12 13:09 UTC
Since tuesdays classic update Molinari no longer works. My modifier key is alt. when I press alt and hover over an item to disenchant the item no longer has the sparkle effect and clicking on an item doesn't do anything, I don't have any other professions to test with to see if the issue is the same on other characters. 

When I first login to the game this error happens 

Date: 2019-12-12 04:53:29
ID: 1
Error occured in: Global
Count: 2
Message: ...dOns\Molinari\libs\LibProcessable\LibProcessable.lua line 264:
   attempt to call global 'GetProfessions' (a nil value)
Debug:
   [C]: GetProfessions()
   ...dOns\Molinari\libs\LibProcessable\LibProcessable.lua:264:
      ...dOns\Molinari\libs\LibProcessable\LibProcessable.lua:250
Locals:

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.6 
  AdiBags, vv1.9.17-classic
  AdvancedInterfaceOptions, v1.3.3-3-g58f2fa4
  AlreadyKnown, v1.22
  Armory, vv1.4
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.4.2
  AtlasLootClassicData, vv1.4.2
  AtlasLootClassicDungeonsAndRaids, vv1.4.2
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.11.58
  ATTClassic, v0.1.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v8.1.0
  AutoAmmo, v1.1.3
  AutoBiographer, v0.3.6
  AutoDismount, v1.0.3
  AutolootEnable, v1.0
  AutoTrackQuests, v1.2
  BankStack, vv11302.0
  Bartender4, v4.8.8
  BasicChatMods, vv4-classic
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterAutoLoot, v1.0.4
  BetterVendorPrice, vv1.11.00
  BlizzMove, v1.9
  BootyBayGazette, v6.1.20191209
  buffOmat, v1.11
  ClassicSpellActivations, v
  Cleanup, v
  ColoredInventoryItems, v1.4
  ComboWhore, v1.1
  DBMCore, v1.13.24
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r039
  DTweaks, v1.4
  DungeonFinder, v0.1.7
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FieldGuide, vv1.5-release
  FleecingTip, v113.1475(011019)
  GatherMate2, v1.45.5
  GigaAutoResourcesTracker, v0.0.1
  GuildTooltip, v2.4.5
  HandyNotes, vv1.5.9-1-g81432ff
  HandyNotesNPCsClassic, v1.21
  HandyNotesTravelGuideClassic, vv2.1.6
  HideQuestTracker, v1.0
  Immersion, v1.2.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.39
  LeatrixPlus, v1.13.40
  LockboxCracker, v1.13.2 build 2
  MacroMakerclassic, v1.5
  MageButtons, v1.01
  MissingTradeSkillsList, v1.13.27
  Molinari, v80200.63-Release
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  NeatPlates, v1.13.2.49
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v8.2.5
  PeaceAndQuiet, v8.2.0
  Puggle, v2.8
  Questie, v5.3.1
  QuestXP, v0.3
  Recount, vv1.13.3a
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SLFG, v1.5
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SLoTe, v
  SortBags, v0.1.3
  SpartanUI, v5.2.13
  SpartanUIArtwork, v5.2.13
  SpartanUIFilmEffects, v5.2.13
  SpartanUIPartyFrames, v5.2.13
  SpartanUIPlayerFrames, v5.2.13
  SpartanUIRaidFrames, v5.2.13
  SpartanUISpinCam, v5.2.13
  SpartanUIStyleFel, v5.2.13
  SpartanUIStyleMinimal, v5.2.13
  SpartanUIStyleTransparent, v5.2.13
  SpartanUIStyleWar, v5.2.13
  StickyTarget, v
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TFTB, v1.10
  TitanClassic, v1.1.4.11302
  TitanClassicAmmo, v1.1.4.11302
  TitanClassicBag, v1.1.4.11302
  TitanClassicClock, v1.1.4.11302
  TitanClassicGold, v1.1.4.11302
  TitanClassicItemDed, v1.0.0.3
  TitanClassicLocation, v1.1.4.11302
  TitanClassicLootType, v1.1.4.11302
  TitanClassicPerformance, v1.1.4.11302
  TitanClassicRegen, v1.1.4.11302
  TitanClassicRepair, v1.1.4.11302
  TitanClassicVolume, v1.1.4.11302
  TitanClassicXP, v1.1.4.11302
  TomPoints, v11302_05
  TomTom, vv11302-1.0.8
  TradeSkillMaster, vv4.8.23
  TradeSkillMasterAppHelper, vv4.0.5
  WeakAuras, v2.15.5
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=ecb)

It appears that the issue occurs when Molinari is running with auctioneer at the same time.  If I disable auctioneer then the error message goes away. Any of Auctioneers suite enabled will cause the error to happen, even if the main addon is disabled but the libraries loaded such as swatter or stubby the error message will keep happening.

**Comment by p3lim** [comment] 2019-12-12 13:39
Duplicate of #37

**Closed by p3lim** 2019-12-12 13:39 UTC
